#!/bin/bash

set -e

cd $1
exec 3>&1 1>&2

INPUT='/tmp/input'
OUTPUT='/tmp/output'

# write STDIN to file
cat > "${INPUT}" <&0 

BOT_TOKEN=$(    jq -r '.source.bot_token      // ""' "${INPUT}")
CHAT_ID=$(      jq -r '.source.chat_id        // ""' "${INPUT}")
CI_URL=$(       jq -r '.source.ci_url         // ""' "${INPUT}")
STATUS=$(       jq -r '.params.status         // ""' "${INPUT}")
MESSAGE_FILE=$( jq -r '.params.message_file   // ""' "${INPUT}")
MESSAGE=$(cat ${MESSAGE_FILE})
BUILD_URL="${CI_URL:=$ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"

ERROR_MSG="Is not defined"
[[ "${BOT_TOKEN:?$ERROR_MSG}" ]]
[[ "${CHAT_ID:?$ERROR_MSG}"   ]]

if [[ "$STATUS" == *"Doc"* ]]; then

OUT_MESSAGE=$( cat <<EOF
<b>${STATUS}</b>
${MESSAGE}
EOF
)

else

OUT_MESSAGE=$( cat <<EOF
<b>${STATUS}</b>
${MESSAGE}
<b>URL:</b> <a href="${BUILD_URL}">Link</a>
<b>Pipeline: </b>${BUILD_PIPELINE_NAME}
<b>Job: </b>${BUILD_JOB_NAME}
<b>Build number: </b>${BUILD_NAME}
EOF
)

fi

RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
                -d "chat_id=${CHAT_ID}" \
                -d "text=${OUT_MESSAGE}" \
                -d "parse_mode=html")

jq -r '. // ""' <<<"${RESPONSE}"

OUTPUT_STRING='{ "version": { "ref": "none"} }'
echo "${OUTPUT_STRING}" >&3
